#! /usr/bin/env python3

from json import load
from random import randint, seed
import sys

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: ./find_unique_movie_pair <path/to/netflix_final_output.json> <cs_login>")
        sys.exit(1)

    outfile = sys.argv[1]
    login = sys.argv[2]

    with open(outfile) as out:
        output = sorted(load(out), key=lambda o: sorted(o[0]))

    seed(login)
    i = randint(0, len(output) - 1)
    print(output[i])
